import { useState } from 'react';
import { Briefcase, Copy, FileText, Loader2, Send } from 'lucide-react';
import { api, type ConfigResponse } from '@/lib/api';
import { usePoll } from '@/lib/hooks';
import type { Settings } from '@/lib/hooks';
import { Button, EmptyState, Mono, Note, Panel, ViewHeader } from './parts';

const TARGET_GROUPS: Record<string, string[]> = {
  'Commercial / public sector': ['dept_of_energy', 'weather_org', 'ai_enterprise', 'depin_vc'],
  Roles: [
    'job_fullstack',
    'job_google',
    'job_openai',
    'job_anthropic',
    'job_cloudflare',
    'job_meta',
    'job_palantir',
  ],
  Internships: ['intern_web3', 'intern_software'],
};

const LABELS: Record<string, string> = {
  dept_of_energy: 'Government / scientific research',
  weather_org: 'Weather & disaster response',
  ai_enterprise: 'Enterprise AI operations',
  depin_vc: 'DePIN / Web3 venture capital',
  job_fullstack: 'Full-stack distributed systems',
  job_google: 'Google — software engineering',
  job_openai: 'OpenAI — AI infrastructure',
  job_anthropic: 'Anthropic — systems',
  job_cloudflare: 'Cloudflare — edge systems',
  job_meta: 'Meta — infrastructure',
  job_palantir: 'Palantir — FDSE',
  intern_web3: 'Web3 / DePIN internship',
  intern_software: 'Software engineering internship',
};

/**
 * Outreach drafting through the server proxy. The draft is generated by a real
 * model call, stored in the node's SQLite database, and the prompt is seeded
 * with the network's real figures so nothing in it is invented.
 */
export function OutreachView({ settings }: { settings: Settings }) {
  const config = usePoll<ConfigResponse>(() => api.config(), 60_000);
  const [target, setTarget] = useState('ai_enterprise');
  const [draft, setDraft] = useState('');
  const [model, setModel] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false);
  const history = usePoll(() => api.pitches(), 20_000);

  const aiReady = Boolean(config.data?.ai.configured) || Boolean(settings.geminiKey.trim());

  const generate = async () => {
    setBusy(true);
    setError(null);
    setDraft('');
    try {
      const response = await api.pitch({
        target,
        settings: {
          userName: settings.userName,
          jobTitle: settings.jobTitle,
          userPhone1: settings.userPhone1,
          userPhone2: settings.userPhone2,
        },
        apiKey: settings.geminiKey.trim() || undefined,
      });
      setDraft(response.text);
      setModel(response.model);
      history.refresh();
    } catch (err: any) {
      setError(err?.message ?? String(err));
    } finally {
      setBusy(false);
    }
  };

  return (
    <div>
      <ViewHeader
        icon={Briefcase}
        title="Outreach Studio"
        subtitle="Drafts are generated by a real model call and archived in the node database"
        actions={
          <Button size="sm" onClick={generate} disabled={busy}>
            {busy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Send className="w-4 h-4" />}
            {busy ? 'Drafting…' : 'Draft email'}
          </Button>
        }
      />

      {!aiReady && (
        <div className="mb-4">
          <Note tone="warn">
            No Gemini key is configured. Add <Mono>GEMINI_API_KEY</Mono> on the server or paste a key in Settings — until then the
            generator will report the provider error instead of producing a fake draft.
          </Note>
        </div>
      )}

      {error && (
        <div className="mb-4">
          <Note tone="bad">{error}</Note>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Panel title="Target">
          <div className="space-y-3">
            {Object.entries(TARGET_GROUPS).map(([group, targets]) => (
              <div key={group}>
                <div className="text-[10px] uppercase tracking-widest text-zinc-600 font-bold mb-1.5">{group}</div>
                <div className="space-y-1">
                  {targets.map((value) => (
                    <button
                      key={value}
                      onClick={() => setTarget(value)}
                      className={`w-full text-left px-2.5 py-1.5 rounded border text-xs transition-colors ${
                        target === value
                          ? 'border-emerald-500/50 bg-emerald-500/10 text-emerald-300'
                          : 'border-zinc-800 text-zinc-400 hover:border-zinc-700'
                      }`}
                    >
                      {LABELS[value] ?? value}
                    </button>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </Panel>

        <Panel title="Draft" className="lg:col-span-2" right={model ? <Mono>{model}</Mono> : undefined}>
          {!draft && !busy && <EmptyState>Pick a target and draft an email.</EmptyState>}
          {busy && <EmptyState>Waiting for the model…</EmptyState>}
          {draft && (
            <>
              <pre className="text-xs text-zinc-300 whitespace-pre-wrap font-sans leading-relaxed">{draft}</pre>
              <div className="mt-3 flex gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    void navigator.clipboard.writeText(draft);
                    setCopied(true);
                    window.setTimeout(() => setCopied(false), 2000);
                  }}
                >
                  <Copy className="w-3.5 h-3.5" /> {copied ? 'Copied' : 'Copy'}
                </Button>
                <a
                  href={`mailto:?subject=${encodeURIComponent(`Gaia Protocol — ${LABELS[target] ?? target}`)}&body=${encodeURIComponent(draft)}`}
                  className="inline-flex items-center gap-2 px-3 py-1.5 text-xs rounded-md bg-zinc-900 border border-zinc-800 text-zinc-300 hover:border-emerald-500/40"
                >
                  <Send className="w-3.5 h-3.5" /> Open in mail client
                </a>
              </div>
            </>
          )}
        </Panel>
      </div>

      <div className="mt-4">
        <Panel title="Archived drafts (server database)" right={<Mono>{history.data?.pitches.length ?? 0} stored</Mono>}>
          <div className="space-y-2 max-h-[220px] overflow-y-auto custom-scrollbar pr-1">
            {(history.data?.pitches ?? []).length === 0 && <EmptyState>Nothing generated yet.</EmptyState>}
            {history.data?.pitches.map((pitch: any) => (
              <div key={pitch.id} className="rounded border border-zinc-800 p-2 bg-zinc-950/60">
                <div className="flex items-center justify-between gap-2 mb-1">
                  <span className="text-[11px] text-zinc-300 font-bold">{LABELS[pitch.target] ?? pitch.target}</span>
                  <Mono className="text-zinc-600">
                    {pitch.model ?? 'unknown model'} · {String(pitch.created_at).slice(0, 19).replace('T', ' ')}
                  </Mono>
                </div>
                <div className="text-[11px] text-zinc-500 line-clamp-3">{String(pitch.pitch).slice(0, 300)}…</div>
                <button
                  onClick={() => {
                    setDraft(pitch.pitch);
                    setModel(pitch.model);
                  }}
                  className="mt-1 inline-flex items-center gap-1 text-[10px] text-emerald-400 hover:underline"
                >
                  <FileText className="w-3 h-3" /> Load this draft
                </button>
              </div>
            ))}
          </div>
        </Panel>
      </div>
    </div>
  );
}
